"""S-10 Knowledge Projection — project understanding bundles to knowledge/.

Reads understanding_bundle.json from the latest run for each pilot config
and produces the knowledge/{family}/{platform}/ artifact tree.

Usage:
    python scripts/project_knowledge.py [--bundle-dir runs/] [--output knowledge/]
"""
from __future__ import annotations

import hashlib
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

import yaml


def _sanitize_cell(text: str, max_len: int = 80) -> str:
    """Collapse multiline text to first line + ellipsis for use in markdown table cells."""
    if not isinstance(text, str):
        text = str(text)
    # Take first non-empty line
    first_line = text.split("\n")[0].strip()
    if not first_line and "\n" in text:
        first_line = text.replace("\n", " ").strip()
    if len(first_line) > max_len:
        return first_line[:max_len] + "…"
    if "\n" in text and first_line != text.strip():
        return first_line + "…"
    return first_line


def _sha256(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def _find_latest_bundles(runs_dir: Path) -> Dict[str, Path]:
    """Find the latest understanding_bundle.json per family/platform."""
    bundles: Dict[str, Path] = {}
    if not runs_dir.exists():
        return bundles

    # Sort run dirs by name (timestamp-based) descending
    run_dirs = sorted(runs_dir.iterdir(), key=lambda p: p.name, reverse=True)
    for run_dir in run_dirs:
        bundle_path = run_dir / "understanding_bundle.json"
        if not bundle_path.exists():
            continue
        # Parse family/platform from run dir name: YYMMDD_HHMMSS_family_platform_hash
        parts = run_dir.name.split("_")
        if len(parts) < 5:
            continue
        # family is parts[2], platform is parts[3]
        family = parts[2]
        platform = parts[3]
        key = f"{family}/{platform}"
        if key not in bundles:
            bundles[key] = bundle_path
    return bundles


def _render_api_surface_md(bundle: Dict[str, Any], product: Dict[str, Any]) -> str:
    """Render api_surface.md from the bundle."""
    display = product.get("display_name", "Unknown")
    family = product.get("family", "?")
    platform = product.get("platform", "?")
    source = f"phase_store/{family}/{platform}/understand.json"
    sha = product.get("repo_sha", "unknown")

    lines = [
        f"# API Surface — {display}",
        f"<!-- Generated by S-10 knowledge-project from {source} -->",
        f"<!-- repo_sha: {sha} -->",
        "",
    ]

    api = bundle.get("api_surface", {})
    class_briefs = api.get("class_briefs", [])
    public_classes = api.get("public_classes", [])
    api_identifiers = api.get("api_identifiers", [])

    if not class_briefs and not public_classes and not api_identifiers:
        lines.append("_No public classes extracted._")
        return "\n".join(lines) + "\n"

    # Use class_briefs if available (rich), fall back to public_classes (names only)
    if class_briefs:
        for cls in class_briefs:
            if isinstance(cls, str):
                lines.append(f"## {cls}")
                lines.append("")
                continue
            name = cls.get("name", "Unknown")
            lines.append(f"## {name}")
            if cls.get("docstring_snippet"):
                lines.append(f"{cls['docstring_snippet']}")

            # Typed methods (richer)
            typed_methods = cls.get("typed_methods", [])
            if typed_methods:
                lines.append("")
                lines.append("| Method | Return Type | Static |")
                lines.append("|--------|-------------|--------|")
                for m in typed_methods:
                    if isinstance(m, dict):
                        mname = m.get("name", "?")
                        ret = _sanitize_cell(m.get("return_type", "void"))
                        static = "yes" if m.get("is_static") else "no"
                        lines.append(f"| `{mname}` | `{ret}` | {static} |")
            elif cls.get("methods"):
                # Simple method name list
                methods = cls["methods"]
                lines.append("")
                lines.append("**Methods**: " + ", ".join(f"`{m}`" for m in methods if isinstance(m, str)))

            props = cls.get("properties", [])
            if props:
                lines.append("")
                lines.append("**Properties**: " + ", ".join(f"`{p}`" if isinstance(p, str) else f"`{p.get('name', '?')}`" for p in props))
            lines.append("")
    elif public_classes:
        # Just class names
        lines.append("| Class |")
        lines.append("|-------|")
        for name in public_classes:
            lines.append(f"| `{name}` |")
        lines.append("")
    elif api_identifiers:
        # Flat identifier list — group by likely class (dotted prefix) vs standalone
        classes = sorted(set(
            ident.rsplit(".", 1)[0] for ident in api_identifiers if "." in ident
        ))
        standalone = sorted(set(
            ident for ident in api_identifiers if "." not in ident
        ))
        if classes:
            lines.append(f"_Extracted {len(api_identifiers)} API identifiers across {len(classes)} classes._")
            lines.append("")
            lines.append("| Class |")
            lines.append("|-------|")
            for cls in classes:
                lines.append(f"| `{cls}` |")
            lines.append("")
        if standalone:
            lines.append("**Top-level identifiers**: " + ", ".join(f"`{s}`" for s in standalone[:50]))
            if len(standalone) > 50:
                lines.append(f"_…and {len(standalone) - 50} more._")
            lines.append("")

    return "\n".join(lines) + "\n"


def _render_claims_md(bundle: Dict[str, Any], product: Dict[str, Any]) -> str:
    """Render claims.md from the bundle."""
    display = product.get("display_name", "Unknown")
    family = product.get("family", "?")
    platform = product.get("platform", "?")
    source = f"phase_store/{family}/{platform}/understand.json"
    sha = product.get("repo_sha", "unknown")
    claims = bundle.get("claims", [])
    ts = _now_iso()

    lines = [
        f"# Claims — {display}",
        f"<!-- Generated by S-10 knowledge-project from {source} -->",
        f"<!-- repo_sha: {sha} | claim_count: {len(claims)} | generated: {ts} -->",
        "",
    ]

    for c in claims:
        cid = c.get("claim_id", "?")
        lines.append(f"## {cid}")
        lines.append(f"**Text**: {c.get('text', '')}")
        lines.append(f"**Kind**: {c.get('kind', '?')}")
        lines.append(f"**Confidence**: {c.get('confidence', '?')}")
        lines.append(f"**Source**: {c.get('claim_source', '?')}")

        evidence = c.get("evidence", [])
        if evidence:
            lines.append("**Evidence**:")
            for e in evidence:
                if isinstance(e, dict):
                    # Keys vary: source_file+snippet+line_start or location+text
                    loc = e.get("source_file", e.get("location", e.get("file", "?")))
                    line_start = e.get("line_start", e.get("line", ""))
                    line_end = e.get("line_end", "")
                    txt = e.get("snippet", e.get("text", ""))
                    if line_start:
                        loc_str = f"{loc}:{line_start}"
                        if line_end and line_end != line_start:
                            loc_str += f"-{line_end}"
                    else:
                        loc_str = str(loc)
                    if txt:
                        # Truncate long snippets
                        txt_short = txt[:120] + "…" if len(txt) > 120 else txt
                        lines.append(f"- `{loc_str}` — {txt_short}")
                    else:
                        lines.append(f"- `{loc_str}`")
                else:
                    lines.append(f"- {e}")
        else:
            lines.append("**Evidence**: _none_")

        snippet_ids = c.get("snippet_ids", [])
        if snippet_ids:
            lines.append(f"**Snippets**: {', '.join(snippet_ids)}")
        else:
            lines.append("**Snippets**: _none_")
        lines.append("")

    return "\n".join(lines) + "\n"


def _render_formats_md(bundle: Dict[str, Any], product: Dict[str, Any]) -> str:
    """Render formats.md from api_surface.format_matrix or product_evidence."""
    display = product.get("display_name", "Unknown")

    # Primary source: api_surface.format_matrix (rich dicts with can_import/can_export)
    api = bundle.get("api_surface", {})
    format_matrix = api.get("format_matrix", [])

    # Fallback source: product_evidence.supported_formats (plain strings)
    pe = bundle.get("product_evidence", {})
    supported_formats = pe.get("supported_formats", [])
    input_formats = {f.lower() for f in pe.get("input_formats", [])}
    output_formats = {f.lower() for f in pe.get("output_formats", [])}

    lines = [
        f"# Format Support — {display}",
        "<!-- Generated by S-10 from api_surface.format_matrix / product_evidence -->",
        "",
    ]

    if not format_matrix and not supported_formats:
        lines.append("_No format data extracted._")
        return "\n".join(lines) + "\n"

    lines.append("| Format | Extension | Import | Export | Confidence |")
    lines.append("|--------|-----------|--------|--------|------------|")

    if format_matrix:
        # Rich format data from format_matrix
        for fmt in format_matrix:
            if not isinstance(fmt, dict):
                lines.append(f"| {fmt} | — | ? | ? | — |")
                continue
            name = fmt.get("name", fmt.get("format", "?"))
            ext = fmt.get("extension", "")
            if isinstance(ext, list):
                ext = ", ".join(ext)
            imp = "yes" if fmt.get("can_import", False) else "no"
            exp = "yes" if fmt.get("can_export", False) else "no"
            conf = fmt.get("confidence", "—")
            if isinstance(conf, float):
                conf = f"{conf:.0%}"
            lines.append(f"| {name} | {ext} | {imp} | {exp} | {conf} |")
    else:
        # Plain string formats — cross-reference with input/output lists
        for fmt in supported_formats:
            if isinstance(fmt, dict):
                name = fmt.get("name", fmt.get("format", "?"))
            else:
                name = str(fmt)
            name_lower = name.lower()
            imp = "yes" if name_lower in input_formats else "—"
            exp = "yes" if name_lower in output_formats else "—"
            lines.append(f"| {name} | — | {imp} | {exp} | — |")

    return "\n".join(lines) + "\n"


def _render_install_md(bundle: Dict[str, Any], product: Dict[str, Any]) -> str:
    """Render install.md from shared_facts."""
    display = product.get("display_name", "Unknown")
    sf = bundle.get("repo", {}).get("shared_facts", {})
    install_cmd = sf.get("install_command", "")
    pkg = sf.get("package_name", "")
    version = sf.get("version", "")
    canonical = product.get("canonical_import", "")

    lines = [
        f"# Installation — {display}",
        "<!-- Generated by S-10 from product_evidence.install_recipe -->",
        "",
        "## Install Command",
    ]

    if install_cmd:
        lines.append(f"```")
        lines.append(install_cmd)
        lines.append("```")
    else:
        lines.append("_No install command detected._")

    if pkg:
        ver_str = f" {version}" if version else ""
        lines.append(f"\n**Package**: `{pkg}{ver_str}`")

    if canonical:
        lines.append(f"\n## Verification")
        lines.append(f"```")
        lines.append(f"// Import {canonical} in your project")
        lines.append(f"```")

    return "\n".join(lines) + "\n"


def _render_limitations_md(bundle: Dict[str, Any], product: Dict[str, Any]) -> str:
    """Render limitations.md from product_evidence."""
    display = product.get("display_name", "Unknown")
    pe = bundle.get("product_evidence", {})
    limitations = pe.get("limitations", [])

    lines = [
        f"# Limitations — {display}",
        "<!-- Generated by S-10 from product_evidence.limitations -->",
        "",
    ]

    if not limitations:
        lines.append("_No limitations extracted._")
        return "\n".join(lines) + "\n"

    rendered = 0
    for lim in limitations:
        if isinstance(lim, dict):
            # Primary text is in "constraint", fallback to "text"
            constraint = lim.get("constraint", lim.get("text", ""))
            if not constraint:
                continue
            source = lim.get("source_file", lim.get("source", ""))
            source_line = lim.get("source_line")
            src_ref = ""
            if source:
                src_ref = f" _(source: {source}"
                if source_line:
                    src_ref += f":{source_line}"
                src_ref += ")_"
            lines.append(f"- {constraint}{src_ref}")
            rendered += 1
        else:
            lines.append(f"- {lim}")
            rendered += 1

    if rendered == 0:
        lines.append("_No limitations extracted._")
    return "\n".join(lines) + "\n"


def _render_model_yaml(bundle: Dict[str, Any], product: Dict[str, Any], bundle_path: Optional[Path] = None) -> str:
    """Render model.yaml metadata."""
    family = product.get("family", "?")
    platform = product.get("platform", "?")
    tier = bundle.get("richness_tier", {})
    claims = bundle.get("claims", [])
    snippets = bundle.get("snippets", [])
    api = bundle.get("api_surface", {})

    # Use actual bundle path relative to project root when available
    if bundle_path is not None:
        try:
            project_root = Path(__file__).resolve().parents[1]
            source = str(bundle_path.resolve().relative_to(project_root)).replace("\\", "/")
        except ValueError:
            source = str(bundle_path)
    else:
        source = f"runs/unknown/{family}_{platform}/understanding_bundle.json"

    model = {
        "family": family,
        "platform": platform,
        "display_name": product.get("display_name", "?"),
        "canonical_import": product.get("canonical_import", ""),
        "repo_url": product.get("repo_url", ""),
        "repo_sha": product.get("repo_sha", ""),
        "bundle_source": source,
        "ingested_at": _now_iso(),
        "richness_tier": tier.get("tier", "?") if isinstance(tier, dict) else str(tier),
        "claim_count": len(claims),
        "snippet_count": len(snippets),
        "api_confidence": "high" if len(api.get("public_classes", [])) > 50 else (
            "medium" if len(api.get("public_classes", [])) > 10 else "low"
        ),
        # TC-5166: Content OS provenance fields
        "last_verified_at": None,
        "pending_maintenance_action": None,
        "content_index_path": f"knowledge/{family}/{platform}/content_index.yaml",
    }
    return yaml.dump(model, default_flow_style=False, sort_keys=False)


def _write_snippets(
    bundle: Dict[str, Any],
    output_dir: Path,
    platform: str,
) -> None:
    """Write snippet files and index."""
    snippets = bundle.get("snippets", [])
    if not snippets:
        return

    snippets_dir = output_dir / "snippets"
    snippets_dir.mkdir(parents=True, exist_ok=True)

    ext_map = {
        "python": ".py", "java": ".java", "dotnet": ".cs",
        "typescript": ".ts", "javascript": ".js", "go": ".go",
        "rust": ".rs", "php": ".php", "ruby": ".rb",
        "kotlin": ".kt", "swift": ".swift", "cpp": ".cpp",
    }
    ext = ext_map.get(platform, ".txt")

    index_entries: List[Dict[str, Any]] = []
    for i, snip in enumerate(snippets, 1):
        filename = f"snippet_{i:03d}{ext}"
        code = snip.get("code", "")
        (snippets_dir / filename).write_text(code, encoding="utf-8")
        index_entries.append({
            "id": filename,
            "source_file": snip.get("source_file", ""),
            "source_type": snip.get("source_type", ""),
            "language": snip.get("language", platform),
            "claim_ids": snip.get("claim_ids", []),
            "line_start": snip.get("line_start"),
            "line_end": snip.get("line_end"),
        })

    (snippets_dir / "snippets_index.json").write_text(
        json.dumps(index_entries, indent=2), encoding="utf-8"
    )


def _write_sync_manifest(output_dir: Path, artifacts: Dict[str, str], source_hash: str) -> None:
    """Write sync_manifest.yaml with SHA256 of each artifact."""
    ts = _now_iso()
    manifest: Dict[str, Any] = {
        "last_full_sync": ts,
        "source_hash": f"sha256:{source_hash}",
        "artifacts": {},
    }
    for name, content in artifacts.items():
        manifest["artifacts"][name] = {
            "sha256": _sha256(content),
            "last_synced": ts,
            "vector_ids": [],
        }
    (output_dir / "sync_manifest.yaml").write_text(
        yaml.dump(manifest, default_flow_style=False, sort_keys=False),
        encoding="utf-8",
    )


def project_bundle(bundle_path: Path, output_root: Path) -> str:
    """Project a single understanding bundle to knowledge/."""
    try:
        return _project_bundle_inner(bundle_path, output_root)
    except Exception as exc:  # noqa: BLE001
        return f"ERROR {bundle_path.name}: {exc}"


def _project_bundle_inner(bundle_path: Path, output_root: Path) -> str:
    """Inner (non-isolated) projection logic."""
    with open(bundle_path, encoding="utf-8") as f:
        bundle = json.load(f)

    product = bundle.get("product", {})
    family = product.get("family")
    platform = product.get("platform")
    if not family or not platform:
        return f"SKIP {bundle_path}: missing family/platform in product"

    output_dir = output_root / family / platform
    output_dir.mkdir(parents=True, exist_ok=True)

    # Compute source hash
    raw = bundle_path.read_bytes()
    source_hash = hashlib.sha256(raw).hexdigest()

    # Check idempotency
    manifest_path = output_dir / "sync_manifest.yaml"
    if manifest_path.exists():
        existing = yaml.safe_load(manifest_path.read_text(encoding="utf-8"))
        existing_hash = (existing or {}).get("source_hash", "")
        if existing_hash == f"sha256:{source_hash}":
            return f"SKIP {family}/{platform}: unchanged (hash match)"

    # Render artifacts
    artifacts: Dict[str, str] = {}
    artifacts["api_surface.md"] = _render_api_surface_md(bundle, product)
    artifacts["claims.md"] = _render_claims_md(bundle, product)
    artifacts["formats.md"] = _render_formats_md(bundle, product)
    artifacts["install.md"] = _render_install_md(bundle, product)
    artifacts["limitations.md"] = _render_limitations_md(bundle, product)

    model_yaml = _render_model_yaml(bundle, product, bundle_path)

    # Write text artifacts
    for name, content in artifacts.items():
        (output_dir / name).write_text(content, encoding="utf-8")

    # Write model.yaml
    (output_dir / "model.yaml").write_text(model_yaml, encoding="utf-8")

    # Write snippets
    _write_snippets(bundle, output_dir, platform)

    # Write JSON artifacts
    api_surface = bundle.get("api_surface", {})
    (output_dir / "api_surface.json").write_text(
        json.dumps(api_surface, indent=2, ensure_ascii=False), encoding="utf-8"
    )
    claims = bundle.get("claims", [])
    (output_dir / "claims.json").write_text(
        json.dumps(claims, indent=2, ensure_ascii=False), encoding="utf-8"
    )

    # Write sync manifest
    _write_sync_manifest(output_dir, artifacts, source_hash)

    snippet_count = len(bundle.get("snippets", []))
    claim_count = len(claims)
    api_count = len(api_surface.get("public_classes", []))
    return f"OK {family}/{platform}: {claim_count} claims, {snippet_count} snippets, {api_count} API classes"


def main() -> None:
    import argparse
    parser = argparse.ArgumentParser(description="Project understanding bundles to knowledge/")
    parser.add_argument("--runs-dir", default="runs", help="Directory containing run folders")
    parser.add_argument("--output", default="knowledge", help="Output knowledge directory")
    parser.add_argument("--bundle", help="Project a specific bundle file instead of auto-discovering")
    args = parser.parse_args()

    project_root = Path(__file__).resolve().parents[1]
    output_root = project_root / args.output

    if args.bundle:
        bundle_path = Path(args.bundle)
        if not bundle_path.exists():
            print(f"ERROR: Bundle not found: {bundle_path}")
            sys.exit(1)
        result = project_bundle(bundle_path, output_root)
        print(result)
        return

    runs_dir = project_root / args.runs_dir
    bundles = _find_latest_bundles(runs_dir)

    if not bundles:
        print("No understanding bundles found.")
        sys.exit(1)

    print(f"Found {len(bundles)} latest bundles:")
    for key, path in sorted(bundles.items()):
        print(f"  {key}: {path.parent.name}")

    print()
    for key, path in sorted(bundles.items()):
        result = project_bundle(path, output_root)
        print(result)


if __name__ == "__main__":
    main()
